[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "pupil-pthreads-win;platform_system == \"Windows\""
]
build-backend = "setuptools.build_meta"
